on:
  push:
    branches: [master]

jobs:
  lints:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop --impure -c bash -c "cabal update; cabal run site build"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto generate /docs"
          branch: ${{ github.head_ref }}
